### ISSUE TITLE
137페이지 내용 문의

### ISSUE THREAD

**Issue by kkyoung67** [DNRY/dlopt#1]
안녕하세요, 
궁금한 사항이 있어서 문의 드립니다.
여기에 수학기호를 표시하는데 익숙하지 않아서 문의내용을 이미지로 첨부해서 보내드립니다. 
감사합니다.

<img width="423" alt="Screen Shot 2020-03-10 at 11 42 48 AM" src="https://user-images.githubusercontent.com/31176340/76274677-a5067f80-62c4-11ea-8cac-47b986e4b47b.png">

**Comment by yoon-gu** [comment]
안녕하세요.
말씀해주신 부분이 맞습니다.
`X`의 크기는 (5,2)이고 `w`의 크기는 (2,1)이므로 `b`의 크기는 (5,1)이어야합니다.
말씀하신 2가지 모두 맞는 표현이지만 첫번째가 더 정확한 표현입니다.

<img width="274" alt="Screen Shot 2020-03-10 at 4 00 04 PM" src="https://user-images.githubusercontent.com/13851374/76287958-fd4f7880-62e8-11ea-9b53-8c3641209f89.png">


오탈자로 인해 혼동을 드려서 죄송하고, 지적해주셔서 감사합니다.

**Comment by yoon-gu** [comment]
말씀해주신 부분은 많은 분들이 볼 수 있도록 Repository README.md에 추가했습니다. 감사합니다.
[https://github.com/DNRY/dlopt/blob/master/README.md#2-137-page-수식-오탈자](https://github.com/DNRY/dlopt/blob/master/README.md#2-137-page-수식-오탈자)

**Comment by kkyoung67** [comment]
답변 감사합니다.
그럼, 135페이지 상단에 있는 식에서도 b의 크기는 (5,1) 로 변경하는게 좋을 것 같습니다.

![image](https://user-images.githubusercontent.com/31176340/76320292-d4000e00-6323-11ea-905f-160fb2a5acb7.png)

**Comment by yoon-gu** [comment]
네. 감사합니다. 아래 링크에 반영하였습니다. :)
[https://github.com/DNRY/dlopt#3-135-page-수식-오탈자](https://github.com/DNRY/dlopt#3-135-page-수식-오탈자)

<img width="277" alt="image" src="https://user-images.githubusercontent.com/13851374/76478695-de69f700-644c-11ea-8d53-31900bab7cbd.png">
