### ISSUE TITLE
안녕하세요. 186, 187 페이지 질문드리겠습니다.

### ISSUE THREAD

**Issue by KevinRyu** [DNRY/dlopt#3]
186페이지의 MSE 식은 N분의1, 187페이지 손실함수 코드는 N분의 0.5인데 0.5는 왜 곱해져있는건가요? 인터넷에 MSE 를 찾아보면 N대신 데이터의 자유도로 나눈다.. 또 다른 자료에서는 그냥 1/2로 되어있는데 이론적 배경을 몰라 어떤것이 맞는지 혼동됩니다.. 조언 부탁드리겠습니다.

**Comment by yoon-gu** [comment]
안녕하세요.

## 코드 수정
질문해주신 부분은 수식과 코드를 혼동되게 작성되었습니다. 죄송합니다.
수식으로 소개된 손실함수를 정확하게 구현하기 위해서는 코드를 다음과 같이 변경해야합니다.
(기존의 코드에서 손실함수와 그래디언트에 모두 2를 곱해주었습니다.)

```python
 # 손실함수
def loss(a, b):
    N = len(x_train) 
    val = 0.0
    for i in range(N):
        val += ( a * x_train[i] + b - y_train[i] )**2 
    return val / N

# 손실함수의 a방향 미분 
def loss_grad_a(a, b):
    N = len(x_train) 
    val = 0.0
    for i in range(N):
        er = 2 * (a * x_train[i] + b - y_train[I])
        val += er * x_train[i] 
    return val / N

# 손실함수의 b방향 미분 
def loss_grad_b(a, b):
    N = len(x_train) 
    val = 0.0
    for i in range(N):
        er = 2 * (a * x_train[i] + b - y_train[I])
        val += er
    return val / N
```
이렇게 코드를 바꾸게 되면 수식과 일치하게 됩니다.
이 코드를 돌리시면 [그림 6-16]의 그래프의 title에 소개된 loss 값도 바뀌게 됩니다.
혼동을 드려 다시 한번 죄송합니다.

## 손실함수에 0.5가 곱해져있는 이유
기존 MSE( 단순히 N으로 나눠준 값 )을 사용하게 되면 그래디언트를 구했을 때, 2가 튀어나오게 됩니다.
일반적으로 수학쪽에서는 그래디언트 수식에 계속 2가 따라 붙는 것을 선호하지 않아서, 애초에 MSE자체에 2를 나누어서(0.5를 곱해서) 그래디언트의 수식을 깔끔하게 만드는 관습이 있습니다.

그래서 여러 자료들에서 MSE에 추가적으로 2가 나누어져 있는 경우를 많이 보실 수 있습니다.

## 해결책 요약
제가 불일치하게 작성한 부분을 바로 잡으려면 다음과 같은 2가지 해결책이 있습니다. 마음에 드시는 방향으로 진행하시면 될 것 같습니다.

1. 코드를 위에 소개 된 바와 같이 변경 (손실함수와 그래디언트에 모두 2를 곱함)
이 경우에는 [그림 6-16] 그래프의 title에 있는 loss 값이 변하게 됩니다. (기존보다 2배 커지게 됩니다.)
1. 187페이지 수식 바로 다음에 나오는 문장을 다음과 같이 변경
    - 변경 전: `손실 함수와 손실함수의 그래디언트를 파이썬 함수로 선언하는 코드는 다음과 같습니다.`
    - 변경 후: `손실 함수와 손실함수의 그래디언트를 파이썬 함수로 선언하는 코드는 다음과 같습니다. 코드에서는 수식의 간결함을 위해서 손실함수에 0.5를 곱하여 구현했습니다.`

**Comment by yoon-gu** [comment]
질문에 대한 답변이 되었으면 좋겠습니다. 더 궁금하신 사항있으시면 언제든 문의주세요.

**Comment by KevinRyu** [comment]
안녕하세요 저자님. 설명 감사합니다. 많은 딥러닝 관련책을 가지고있지만 전반적으로 기술을 이해하는데 필요한 필요한 어려운 개념들이 잘
설명되어 있어 개인적으로 너무 맘에 들고 도움이 되고있습니다. 특히 Visualizer로 동작이 설명된 부분과 Optimizer 관련
설명이 많은 도움이 됬습니다. 거기에 궁금한부분 설명까지 해주시니 더 좋네요. 그럼 수고하세요!


2020년 6월 3일 (수) 오전 1:03, Jacob Hwang <notifications@github.com>님이 작성:

**Comment by yoon-gu** [comment]
도움이 되신다니 다행이네요! 

궁금하신 사항은 언제든 Repository로 연락주세요.

감사합니다 :)
