### ISSUE TITLE
텐서보드 관련 문의드립니다.

### ISSUE THREAD

**Issue by Biyong-Jeong** [DNRY/dlopt#6]
안녕하세요.
연속해서 문의드립니다.

Chp15의 텐서보드 공부중입니다.

404페이지 실행하여 정상적으로 웹주소를 받았는데
405페이지와 같은 텐서보드 그림은 안 뜨고 연결될 수 없음만 나옵니다.
관련하여 확인 부탁드립니다.

참고로 제 환경은 다음과 같습니다
 - 사용 PC : Mac
 - 사용 웹브라우저 : Chrome (혹시나 해서 해보니, Safari에서도 실행이 안됩니다.)
 - 기타 : 컴퓨터 사용 폴더에 따라 다르겠지만 명칭은 다 다르나 마지막 :6006은 동일하게 나왔습니다.

**Comment by Biyong-Jeong** [comment]
추가적으로 내부 생성된 폴더 파일 클릭해보니 다음과 같은 메시지가 있습니다.

~~iMac.local is not UTF-8 encoded
Saving disabled.
See Console for more details.

**Comment by yhbyhb** [comment]
안녕하세요.

저도 맥을 사용하는데, 확인을 해보니  같은 증상을 겪었습니다. 
텐서보드가 알려주는 주소로 접속이 안될 경우에는, 
`http://localhost:6006` 를 브라우저에 복사 붙여넣기를 하시면 텐서보드를 볼 수 있을 것입니다.
`localhost` 가 곧 현재 사용하시는 PC의 주소를 의미하기 때문에 결과적으로 같은 페이지를 보는 것 입니다.

**Comment by Biyong-Jeong** [comment]
상기와 같이 알려주신대로 localhost:6006 으로 하니 텐서보드 화면으로는 접속이 되나
하기와 같은 에러가 또 발생하네요...
텐서보드 너무 어렵네요...

터미널에서 주소가 발행되면 정상적으로 되었다고 404페이지에서 보았는데
하기와 같은 에러가 발생했습니다.
어떻게 조치해야 할까요?

![스크린샷 2020-06-25 오후 2 33 02](https://user-images.githubusercontent.com/51958475/85660850-13931000-b6f1-11ea-8e19-2ae2f4017b16.png)

**Comment by yhbyhb** [comment]
남겨주신 스크린샷을 보니 문제의 원인으로 추정되는 것은 아래입니다.

- 텐서보드를 실행한 경로가 해당 명령어를 실행시킨 노트북의 경로와 맞는지,
- 해당명령어를 실행시킨 후, `001_scalar` 의 하위 폴더가 생성되었고, 파일이 생성되었는지,
- 텐서보드 명령어에 들어가는 `001_scalar` 라고 하는 경로를 잘 입력하였는지, 
위 세가지를 확인하시면 텐서보드에 위와 다른 메세지가 나올 것이라고 생각합니다.

**Comment by Biyong-Jeong** [comment]
우선 결론적으로는 알려주신 것들 조합 해보니 다음과 같이 해결이 되었습니다.
![스크린샷 2020-06-29 오전 11 39 44](https://user-images.githubusercontent.com/51958475/85967469-80621f00-b9fd-11ea-83d5-95cb9d87ab84.png)

책에서 말씀하신거는 주피터 노트북의 터미널을 이용하면 다음과 같이
activate 하는 게 에러가 나고 제가 무시하고 tensorboar~ 를 하고서 웹주소로 접속하면 에러가 났습니다.
(해당 노트북을 들어가기 전 activate 한 환경은 deep-learning 환경입니다)

![스크린샷 2020-06-29 오전 11 36 03](https://user-images.githubusercontent.com/51958475/85967642-e77fd380-b9fd-11ea-99aa-ee5ccb5624a3.png)


그래서 Mac Terminal을 새 창을 띄우고 404페이지 대로 실행하니 맨 처음과 같이 정상 실행이 되었습니다.

혹시 주피터 터미널은 왜 에러가 나는 건지와 앞으로는 맥 터미널로 말씀드린대로 사용해도 무방한지요?
마지막으로 조언 부탁드립니다.

**Comment by yhbyhb** [comment]
먼저 답변이 늦어서 죄송합니다.

잘 진행이 되어서 다행입니다.
결론 부터 말씀드리자면 mac 의 terminal을 이용하셔도 무방합니다. conda activate deep-learning으로 환경만 맞추면 정상작동 합니다.

위의 주피터 노트북의 터미널에서 나온 에러메세지는 anaconda 설정과 관계가 있는 메세지 입니다.
최신 macOS Catalina 에서 anaconda를 사용할 때 겪는 문제입니다.
`conda init zsh` 를 Mac terminal에서 실행하고 터미널을 껏다가 다시 키면 해당 에러메세지가 사라지실 것입니다.

**Comment by Biyong-Jeong** [comment]
네. 감사합니다.
당분간은 mac terminal로 사용해야 겠습니다.
