### ISSUE TITLE
19장 GAN 관련 문의드립니다.

### ISSUE THREAD

**Issue by Biyong-Jeong** [DNRY/dlopt#8]
안녕하세요.

미천한 실력으로 지속적으로 질문드려 번거롭게 하는 점 양해 부탁드립니다.
476페이지 마지막 실행을 하니 다음과 같은 에러가 발생하였습니다.
확인 및 조언 부탁드립니다.
(배경 설명 : Mac에서 하니 gpu가 없어 epoch는 10회만 실시하였습니다. )

![스크린샷 2020-07-01 오전 1 31 20](https://user-images.githubusercontent.com/51958475/86152279-e902e600-bb3a-11ea-9e0c-37f583ba80c6.png)

감사합니다.

**Comment by yhbyhb** [comment]
해당 에러는 checkpoints 라는 하위폴더가 만들어지지 않아서 생기는 에러입니다.
페이지472의 아래 코드가 정상적으로 실행이 안 된것 같습니다.
```python
saver.save(sess, './checkpoints/generator.ckpt')
```

[19장 노트북 파일](https://github.com/DNRY/dlopt/blob/master/notebooks/CH19.ipynb)을 참고 하시면 도움이 될것 같습니다.

**Comment by Biyong-Jeong** [comment]
해당 폴더를 만들고 그 밖의 폴더에 생성이 되게 하여 오류가 났었습니다.
해당 사항 확인하였습니다.
감사합니다.
